### ISSUE TITLE
lapidist run as UTF-8

### ISSUE THREAD

**Issue by opoudjis** [metanorma/lapidist#9]
````
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
````

is set on Gemfile. However, lapidist is still running with default encoding of ASCII. As a result, sometimes SimpleCov crashes; e.g. for metanorma-nist:

````
Coverage report generated for RSpec to /Users/nickn/Documents/Arbeit/upwork/ribose/metanorma-nist/coverage. 1447 / 1608 LOC (89.99%) covered.
SimpleCov failed with exit 1Traceback (most recent call last):
	31: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/exe/rspec:4:in `<main>'
	30: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:45:in `invoke'
	29: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:71:in `run'
	28: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:87:in `run'
	27: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:110:in `run_specs'
	26: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:76:in `report'
	25: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:166:in `finish'
	24: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:186:in `close_after'
	23: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:170:in `block in finish'
	22: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:200:in `notify'
	21: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:200:in `each'
	20: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:201:in `block in notify'
	19: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/formatters/base_text_formatter.rb:32:in `dump_failures'
	18: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/notifications.rb:113:in `fully_formatted_failed_examples'
	17: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/notifications.rb:113:in `each_with_index'
	16: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/notifications.rb:113:in `each'
	15: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/notifications.rb:114:in `block in fully_formatted_failed_examples'
	14: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/notifications.rb:200:in `fully_formatted'
	13: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/formatters/exception_presenter.rb:78:in `fully_formatted'
	12: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/formatters/exception_presenter.rb:86:in `fully_formatted_lines'
	11: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/formatters/exception_presenter.rb:240:in `formatted_message_and_backtrace'
	10: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/formatters/exception_presenter.rb:34:in `colorized_message_lines'
	 9: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/formatters/exception_presenter.rb:149:in `failure_lines'
	 8: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/formatters/exception_presenter.rb:149:in `tap'
	 7: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/formatters/exception_presenter.rb:150:in `block in failure_lines'
	 6: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/formatters/exception_presenter.rb:163:in `failure_slash_error_lines'
	 5: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/formatters/exception_presenter.rb:218:in `read_failed_lines'
	 4: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/formatters/snippet_extractor.rb:30:in `extract_expression_lines_at'
	 3: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/formatters/snippet_extractor.rb:18:in `source_from_file'
	 2: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-core-3.8.2/lib/rspec/core/world.rb:150:in `source_from_file'
	 1: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-support-3.8.2/lib/rspec/support/source.rb:12:in `from_file'
/Users/nickn/.rvm/gems/ruby-2.5.1/gems/rspec-support-3.8.2/lib/rspec/support/source.rb:12:in `read': "\xC2" on US-ASCII (Encoding::InvalidByteSequenceError)
````

The crash happens because the output of rspec is citing native UTF-8 characters in the diffs between expected and actual output (such as em-dashes), and the output encoding is clearly still set to ASCII.

**Comment by opoudjis** [comment]
This gets fixed by using rspec instead of rake.

**Comment by opoudjis** [comment]
... No, it fixes some issues, but not error reporting

**Comment by opoudjis** [comment]
I have tried to fix it as follows:

````
 def self.run_cmd(cmd, options)
    if options[:dry_run] || options[:verbose]
      puts "run system(#{cmd}) pwd:#{Dir.pwd}"
    end

    if !options[:dry_run]
      system({"LC_CTYPE" => 'UTF-8'}, cmd, chdir: Dir.pwd)
    end
  end
````

I have also attempted to add to the start of Gemfile.devel

````
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
````

Neither of them seem to be convincing lapidist to use UTF-8 when it is running "rspec --format doc" (which I need instead of rake, but the same issue of course happens with rake).

I will add that when I run in a new script `system("rspec --format doc")`, it works just fine. So arbitrary ruby scripts are inheriting ENV from environment. lapdist calls to system do not seem to.

Without this resolved, I cannot use this script. And this needs to be resolved to my satisfaction, working on my machine.

**Comment by ronaldtse** [comment]
Seems related to this issue: https://github.com/github/linguist/pull/4465

**Comment by CAMOBAP** [comment]
#14

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you help release a new version? @opoudjis can you check that this issue is resolved? Thanks!

**Comment by opoudjis** [comment]
I ended up changing my locale as well. Working now.
